name:               "Ink"
description:        "A minimalistic jekyll theme for humans"

url:                ""
author:             "thinker3197"
email:              "jhondoe@abc.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "jhondoe"
email:              "jhondoe@abc.com"
github:             "Amadues"
pinterest:          "jhondoe"
linkedin:           "jhondoe"
facebook:           "jhondoe"

disqus_shortname:   "thinker3197"

background:         "https://image.baidu.com/search/detail?ct=503316480&z=0&ipn=d&word=%E5%85%AB%E9%87%8D%E6%A8%B1&step_word=&hs=0&pn=0&spn=2&di=36631263840&pi=0&rn=1&tn=baiduimagedetail&is=3405700413%2C2968031429&istype=2&ie=utf-8&oe=utf-8&in=&cl=2&lm=-1&st=-1&cs=490262593%2C955323892&os=2731147246%2C2792128348&simid=0%2C0&adpicid=0&lpn=0&ln=1987&fr=&fmq=1514898070897_R&fm=result&ic=0&s=undefined&se=&sme=&tab=0&width=&height=&face=undefined&ist=&jit=&cg=&bdtype=17&oriquery=&objurl=http%3A%2F%2Fe.hiphotos.baidu.com%2Fimage%2Fpic%2Fitem%2F34fae6cd7b899e519bb6493949a7d933c8950de6.jpg&fromurl=ippr_z2C%24qAzdH3FAzdH3Fooo_z%26e3B17tpwg2_z%26e3Bv54AzdH3Fks52AzdH3F%3Ft1%3Dmdml8b9na&gsm=0&rpstart=0&rpnum=0"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
