name:               "Ink"
description:        "A minimalistic jekyll theme for humans"

url:                ""
author:             "thinker3197"
email:              "jhondoe@abc.com"
twitter:            "jhondoe"
email:              "jhondoe@abc.com"
github:             "Amadues"
pinterest:          "jhondoe"
linkedin:           "jhondoe"
facebook:           "jhondoe"

disqus_shortname:   "thinker3197"

background:         "http://pic.962.net/up/2017-11/201711610244265.png"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
