name:               "Ink"
description:        "A minimalistic jekyll theme for humans"

url:                ""
author:             "thinker3197"
email:              "jhondoe@abc.com"
twitter:            "jhondoe"
email:              "jhondoe@abc.com"
github:             "Amadues"
pinterest:          "jhondoe"
linkedin:           "jhondoe"
facebook:           "jhondoe"

disqus_shortname:   "thinker3197"

background:         "https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1514908154451&di=672e68da6af7b167c72cc987c18f1601&imgtype=0&src=http%3A%2F%2Fg.hiphotos.baidu.com%2Fimage%2Fpic%2Fitem%2F54fbb2fb43166d22a90167b94d2309f79052d2ad.jpg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
